//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamYaoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int GameID { get; set; }
        public string Payer { get; set; }
        public Nullable<int> Amount { get; set; }
    
        public virtual Fixture Fixture { get; set; }
        public virtual Member Member { get; set; }
    }
}
