CREATE TABLE [dbo].[Payment]
(
	[GameID] INT NOT NULL,
	[Payer] NVARCHAR (20) NOT NULL,
	[Amount] NVARCHAR (50),
	CONSTRAINT PK_PAY PRIMARY KEY (GameID, Payer),
	CONSTRAINT FK_GAME FOREIGN KEY (GameID) REFERENCES Fixture (FixtureId),
	CONSTRAINT FK_PAYER FOREIGN KEY (Payer) REFERENCES Member (Email)
)
